Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("PizzeriaApp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PizzeriaApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "PizzeriaApp"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("pizzas", views.pizzas, name="pizzas"),
    path("pizzas/<int:name_id>/", views.pizza, name="pizza"),
    path("comments/<int:name_id>/", views.comments, name="comments"),
    path("new_comment/<int:name_id>/", views.new_comment, name="new_comment"),
]

PizzeriaApp/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "toppings"

    def __str__(self):
        return self.name


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.text

PizzeriaApp/forms.py
from django import forms
from .models import Comment, Pizza

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text','pizza']
        labels = {'description': 'What would you like to say?'}

PizzeriaApp/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm
from datetime import datetime, date

# Create your views here.
def index(request):
    """Home Page"""
    return render(request, "PizzeriaApp/index.html")


def pizzas(request):
    pizzas = Pizza.objects.order_by("name")

    context = {"pizzas": pizzas}

    return render(request, "PizzeriaApp/pizzas.html", context)


def pizza(request, name_id):
    pizza = Pizza.objects.get(id=name_id)
    toppings = pizza.topping_set.order_by("name")

    context = {"pizza": pizza, "toppings": toppings}

    return render(request, "PizzeriaApp/pizza.html", context)


def comments(request, name_id):
    if request.method == "GET" and request.GET.get("btn1"):
        comment = request.GET.get("comment")
        Comments.objects.create(
            pizza=name_id,
            text=comment,
            date_added=date.today(),
        )
    comments = Comment.objects.filter(pizza=name_id)
    pizza = Pizza.objects.get(id=name_id)

    context = {"pizza": pizza, "comments": comments}
    return render(request, "PizzeriaApp/comments.html", context)


def new_comment(request):
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_post.save()
            return redirect("PizzeriaApp:pizzas")

    context = {"form": form}
    return render(request, "PizzeriaApp/new_comment.html", context)
    

PizzeriaApp/templates/PizzeriaApp/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
    <title>Mamma Mia Pizzeria!</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'PizzeriaApp:index' %}">
            Home</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'PizzeriaApp:pizzas' %}">Pizzas</a>
                </li>
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>




</html>

PizzeriaApp/templates/PizzeriaApp/comments.html
{% extends "PizzeriaApp/base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block content %}

<h2> Pizza: {{pizza.name}} </h2>

<h2><img src="{{pizza.image.url}}" class="img-thumbnail" style="max-height: 300px;" alt=""></h2>

<form method='get'>
    {% for c in comments %}
    <li>
        <p> {{c.text}} -- {{c.date_added}} </p>
    </li>
    {% empty %}
    <li>
        There are no comments for this post.
    </li>
    {% endfor %}

    <p><input type="text" name="comment"></p>
    <p><button type="submit" name="btn1" value=1>Submit Comment</button></p>
</form>

{% endblock content %}

PizzeriaApp/templates/PizzeriaApp/index.html
{% extends "PizzeriaApp/base.html" %}

{% block content %}


<p>
<h1>Mamma Mia Pizzeria!</h1>
</p>

<body style="background-color: brown;"></body>
<img src="https://i.pinimg.com/564x/2f/8e/f6/2f8ef62cab180984976b1a55a880d917.jpg" class="img-thumbnail"
    style="text-align: center;">

<p>
<h6>We pride ourselves on quality hand crafted pizzas,
    from fresh out of the oven to your table!
</h6>
At this time we are not doing delivery to limit the
possibility to spread COVID-19 to keep you and your
loved ones safe. We apologize for the inconvenience
but appreciate your patience!
</p>
{% endblock content %}

PizzeriaApp/templates/PizzeriaApp/new_comment.html
{% extends "PizzeriaApp/base.html" %}

{% block content %}

<p> <a href="{% url 'PizzeriaApp:pizza' pizza.id %}">{{pizza}}</a> </p>

<p> Add a new comment</p>

<form action="{% url 'PizzeriaApp:new_comment' pizza.id %}" method='post'>

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add entry</button>

</form>

{% endblock content %}

PizzeriaApp/templates/PizzeriaApp/pizza.html
{% extends "PizzeriaApp/base.html" %}

{% block content %}

<p>Pizzas: {{pizza}}</p>>

<ul>

    {% for topping in toppings %}
    <li>
        <p>{{topping.name|linebreaks}}</p>
    </li>

    {% empty %}
    <li> There are no toppings listed yet.</li>
    {% endfor %}
</ul>

<p><a href="{% url 'PizzeriaApp:new_comment' pizza.id %}">Add New Comment!</a> </p>

{% endblock content %}

PizzeriaApp/templates/PizzeriaApp/pizzas.html
{% extends "PizzeriaApp/base.html" %}



{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'PizzeriaApp:pizza' pizza.id%}"> {{pizza}} </a>
    </li>
    {% empty %}
    <li> No topics have been added yet. </li>
    {% endfor %}
</ul>


{% endblock content %}